name: build

on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v4

      - name: Create Maven settings.xml with token substitution
        run: |
          if [ -n "${{ vars.QUIZ_ME_UP_MAVEN_SETTINGS_XML }}" ]; then
            # Export the GitHub token and substitute only specific variables
            export QUIZ_ME_UP_GITHUB_TOKEN="${{ secrets.QUIZ_ME_UP_GITHUB_TOKEN }}"
            echo '${{ vars.QUIZ_ME_UP_MAVEN_SETTINGS_XML }}' | envsubst '${QUIZ_ME_UP_GITHUB_TOKEN}' > ./maven/settings.xml
            echo "✅ Maven settings.xml created with GITHUB_TOKEN substitution"
          else
            echo "⚠️  No Maven settings.xml variable found"
          fi

      - name: Build maven image
        run: docker build -t quizmeup/maven ./maven

      - name: Build mongo image
        run: docker build -t quizmeup/mongo ./mongo

      - name: Build mongo-express image
        run: docker build -t quizmeup/mongo-express ./mongo/mongo-express

      - name: Build rabbitmq image
        run: docker build -t quizmeup/rabbitmq ./rabbitmq