name: build

on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v4

      - name: Build maven image
        run: docker build -t quizmeup/maven ./maven

      - name: Build mongo image
        run: docker build -t quizmeup/mongo ./mongo

      - name: Build mongo-express image
        run: docker build -t quizmeup/mongo-express ./mongo/mongo-express

      - name: Build rabbitmq image
        run: docker build -t quizmeup/rabbitmq ./rabbitmq