name: release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        id: next_version
        uses: quiz-me-up/reusable-workflow/.github/actions/next-version@master
        with:
          release_type: ${{ github.event.inputs.release_type }}
          fallback_version: '0.0.0'

      - name: Set up Docker Hub credentials
        uses: quiz-me-up/reusable-workflow/.github/actions/setup-docker-hub@master
        with:
          dockerhub_username: ${{ secrets.QUIZ_ME_UP_DOCKER_USERNAME }}
          dockerhub_password: ${{ secrets.QUIZ_ME_UP_DOCKER_TOKEN }}

      - name: Create Maven settings.xml with token substitution
        run: |
          if [ -n "${{ vars.QUIZ_ME_UP_MAVEN_SETTINGS_XML }}" ]; then
            # Export the GitHub token and substitute only specific variables
            export QUIZ_ME_UP_GITHUB_TOKEN="${{ secrets.QUIZ_ME_UP_GITHUB_TOKEN }}"
            echo '${{ vars.QUIZ_ME_UP_MAVEN_SETTINGS_XML }}' | envsubst '${QUIZ_ME_UP_GITHUB_TOKEN}' > ./maven/settings.xml
            echo "✅ Maven settings.xml created with GITHUB_TOKEN substitution"
          else
            echo "⚠️  No Maven settings.xml variable found"
          fi

      - name: Build Docker images
        run: |
          docker build -t quizmeup/maven:${{ steps.next_version.outputs.version }} -t quizmeup/maven:latest ./maven
          docker build -t quizmeup/mongo:${{ steps.next_version.outputs.version }} -t quizmeup/mongo:latest ./mongo
          docker build -t quizmeup/rabbitmq:${{ steps.next_version.outputs.version }} -t quizmeup/rabbitmq:latest ./rabbitmq
          docker build -t quizmeup/mongo-express:${{ steps.next_version.outputs.version }} -t quizmeup/mongo-express:latest ./mongo/mongo-express

      # Push des images vers Docker Hub
      - name: Push Docker images to Docker Hub
        run: |
          # Push avec tag de version
          docker push quizmeup/maven:${{ steps.next_version.outputs.version }}
          docker push quizmeup/mongo:${{ steps.next_version.outputs.version }}
          docker push quizmeup/rabbitmq:${{ steps.next_version.outputs.version }}
          docker push quizmeup/mongo-express:${{ steps.next_version.outputs.version }}
          
          # Push avec tag latest
          docker push quizmeup/maven:latest
          docker push quizmeup/mongo:latest
          docker push quizmeup/rabbitmq:latest
          docker push quizmeup/mongo-express:latest

      - name: Setup git bot user
        uses: quiz-me-up/reusable-workflow/.github/actions/setup-git-bot-user@master

      - name: Create Tag
        run: |
          git add .
          git commit --allow-empty -m "ci: release ${{ steps.next_version.outputs.full_version }}"
          git tag -a ${{ steps.next_version.outputs.full_version }} -m "release: ${{ steps.next_version.outputs.full_version }}"
          git push origin master --follow-tags

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.QUIZ_ME_UP_GITHUB_TOKEN }}
          tag: ${{ steps.next_version.outputs.full_version }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.next_version.outputs.full_version }}
          name: Release ${{ steps.next_version.outputs.full_version }}
          body: ${{ steps.changelog.outputs.changes }}